---
title: "Econometrie II : Transports"
author: "Guewen HESLAN - Bijan VALILOU"
date: "Janvier 2021"
output:
  pdf_document:
    citation_package: biblatex
    toc: no
    number_sections: yes
    toc_depth: 4
    highlight: tango
    latex_engine: lualatex
    fig_caption: yes
  html_document:
    toc: yes
    toc_depth: 5
subtitle: "Rapport"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot[CO,CE]{Econométrie II}
- \fancyfoot[LE,RO]{\thepage}
bibliography: references.bib
---

```{=tex}
\tableofcontents
\newpage
```

# Introduction

```{r, include=FALSE}
library(usethis)
library(readxl)
library(gitcreds)
library(strucchange)
library(gets)
library(ggplot2)
library(kableExtra)
library(pander)
library(ggpubr)
library(lmtest)
library(tseries)
library(skedastic)
```

```{r, include=FALSE}


Transport_France2019 <- read_excel("Transport_France2019_v2.xlsx")

##Vecteurs des séries
#Qtt_Trsp_route <- Transport_France2019$Qtt_Trsp_route
#Qtt_Trsp_train <- Transport_France2019$Qtt_Trsp_train
#Pdiesel <- Transport_France2019$Pdiesel
#Qdiesel <- Transport_France2019$QDiesel
#GDP <- Transport_France2019$GDP
#CPI <- Transport_France2019$CPI
#QDieselCamion <- Transport_France2019$Qdieselcamion

```

```{r, include=FALSE}
##Séries temporelles
Qtt_Trsp_route.ts <- ts(Transport_France2019$Qtt_Trsp_route, start=c(1985) , end=c(2019), frequency=1)
Qtt_Trsp_train.ts <- ts(Transport_France2019$Qtt_Trsp_train, start=c(1985) , end=c(2019), frequency=1)
Pdiesel.ts <- ts(Transport_France2019$Pdiesel, start=c(1985) , end=c(2019), frequency=1)
Qdiesel.ts <- ts(Transport_France2019$QDiesel, start=c(1985) , end=c(2019), frequency=1)
GDP.ts <- ts(Transport_France2019$"PIB en volume (en milliards d'euros 2014)", start=c(1985) , end=c(2019), frequency=1)
CPI.ts <- ts(Transport_France2019$CPI, start=c(1985) , end=c(2019), frequency=1)
Qdieselcamion.ts <- ts(Transport_France2019$Qdieselcamion, start=c(1985) , end=c(2019), frequency=1)

```

# Présentation des données
```{r, echo=FALSE, out.width = '10%', out.height = '10%', fig.align='center'}
table <- round(Transport_France2019,2)
colnames(table) <- c("Année", "Quantité transportée par routes", "Quantité transportée par train","Prix du disel (euros/litre de diesel)","Quantité de diesel consommé (en milliers de tonnes)","PIB en monnaie constante (base 100=2014)","Indice des prix à la consommation (base 100=2015)","Quantité de diesel consommé des camions (en milliers de tonnes)","PIB en volume (en milliards d’euros 2014)")

kable(table, booktabs = T, linesep = "", caption = "Consommation de gazole des camions") %>% 
kable_styling(latex_options = "hold_position", full_width = T,font_size = 7) %>% 
row_spec(0, bold = T) %>% 
column_spec(1, bold = T) 
```


```{r echo=FALSE, fig.align='center', warning=FALSE, out.height='100%', out.width='100%'}
##Graph en niveau
plt1 <- ggplot() + 
  geom_line( aes(x = Transport_France2019$Year,y = Transport_France2019$Qtt_Trsp_route))+
labs(x = "Année", y = "Quantités transportées \n par route", title = "Fig. 1 Quantités transportées \n par route") + 
    theme(axis.text=element_text(size=5),axis.title=element_text(size=6),title = element_text(size=7), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))


plt2 <- ggplot() + 
  geom_line( aes(x = Transport_France2019$Year,y = Transport_France2019$Qtt_Trsp_train))+
labs(x = "Année", y = "Quantités transportées \n par train", title = "Fig. 2 Quantités transportées \n par train") + 
    theme(axis.text=element_text(size=5),axis.title=element_text(size=6),title = element_text(size=7), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))

plt3 <- ggplot() + 
  geom_line( aes(x = Transport_France2019$Year,y = Transport_France2019$Pdiesel))+
labs(x = "Année", y = "Prix du disel \n (euros/litre de diesel)", title = "Fig. 3 Prix du diesel") + 
    theme(axis.text=element_text(size=5),axis.title=element_text(size=6),title = element_text(size=7), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))

plt4 <- ggplot() + 
  geom_line( aes(x = Transport_France2019$Year,y = Transport_France2019$"PIB en volume (en milliards d'euros 2014)"))+
labs(x = "Année", y = "PIB en volume \n (en milliards d'euros 2014)", title = "Fig. 4 Produit intérieur brut") + 
    theme(axis.text=element_text(size=5),axis.title=element_text(size=6),title = element_text(size=7), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))


plt5 <- ggplot() + 
  geom_line( aes(x = Transport_France2019$Year,y = Transport_France2019$QDiesel))+
labs(x = "Année", y = "Quantité de diesel consommé \n (en milliers de tonnes)", title = "Fig. 5 Quantité totale \n de diesel consommé") + 
    theme(axis.text=element_text(size=5),axis.title=element_text(size=6),title = element_text(size=7), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))

plt6 <- ggplot() + 
  geom_line( aes(x = Transport_France2019$Year,y = Transport_France2019$QDiesel))+
labs(x = "Année", y = "Quantité de diesel consommé \n (milliers de tonnes)", title = "Fig. 6 Quantité de diesel \n consommé par le transport par camion") + 
    theme(axis.text=element_text(size=5),axis.title=element_text(size=6),title = element_text(size=7), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))

plt7 <- ggplot() + 
  geom_line( aes(x = Transport_France2019$Year,y = Transport_France2019$CPI))+
labs(x = "Année", y = "Indice de prix à la consommation \n (base 100 = 2015)", title = "Fig.7 Prix à la consommation") + 
    theme(axis.text=element_text(size=5),axis.title=element_text(size=6),title = element_text(size=7), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))


figure <- ggarrange(plt1, plt2, plt3, plt4,plt5, plt6,"",plt7, ncol=3, nrow = 3, heights = c(1, 1))
annotate_figure(figure,
               top = text_grob("Présentation des variables", face = "bold", size = 14))


```

```{r, echo=FALSE}
n=length(Transport_France2019$Qdieselcamion)

vec <- c(Transport_France2019$Pdiesel/Transport_France2019$CPI,Transport_France2019$"PIB en volume (en milliards d'euros 2014)",Transport_France2019$Qtt_Trsp_route)
X <- matrix( vec, ncol=3) 
Y=matrix(Transport_France2019$Qdieselcamion,n,1)
q=ncol(Y);
k=ncol(X);
K=k+1

 y=Y
 x=X
 
 nobs=cbind(1:n)
 
 OLS=lm(formula = y ~ x)
 
summary(OLS) %>% pander


xc = cbind(1,x) 
bhat = OLS$coefficients 
yf = xc %*% bhat
res = y - yf
scr = t(res) %*% res


d1 = t(res) %*% res
d2 =  t(res[2:n]-res[1:n-1]) %*% (res[2:n]-res[1:n-1])
dw = d2/d1
print (dw)

```


```{r echo=FALSE, warning=FALSE, out.width = '70%', out.height = '70%', fig.align='center'}
Wr <- efp(y ~ x, type = "Rec-CUSUM")
plot(Wr)
#
# Test Cusum Square
#
rr <- (recresid(y ~ x))
rr <- rr^2
cumrr <- cumsum(rr)/scr
#
# Valeurs seuil de la distribution Cusum
#
c0 = 0.18915

kp2=K+1
c0 = 0.18915 # valeur critique de c0

t2 <- ts(kp2:n)
t3=t2-1
smin <-((t2-k)/(n-k))-c0
smax <- ((t2-k)/(n-k))+c0
#
vec2 <- c(smin, cumrr, smax)
cusum2 <- matrix(vec2, ncol = 3); 
matplot(c(t3), cusum2, type ="l")

```

```{r echo=FALSE}
#sctest(y ~ x, type = "Chow", point =)
# pour R, la rupture est test?e non pas sur 1979-1980 mais sur 1979. 
#Sur Eviews, la rupture est test?e sur 1980/
g <- NULL
for(i in 14:18) {

g <- rbind(g,c(1985+i,sctest(y ~ x, type = "Chow", point = i)))
}


kable(g, booktabs = T, linesep = "", caption = "Test de Chow de 1999 à 2003") %>% 
kable_styling(latex_options = "hold_position", full_width = T,font_size = 7) %>% 
  row_spec(0, bold = T) %>% 
column_spec(1, bold = T)
```


```{r echo=FALSE, out.width = '70%', out.height = '70%', fig.align='center'}
n=length(Transport_France2019$Qdieselcamion)

P1 <- replicate(35, 0)
P1[1:16] <-  Transport_France2019$Pdiesel[1:16]/Transport_France2019$CPI[1:16]

P2 <- replicate(35, 0)
P2[17:35] <-  Transport_France2019$Pdiesel[17:35]/Transport_France2019$CPI[17:35]

vec <- c(P1,P2, Transport_France2019$"PIB en volume (en milliards d'euros 2014)",Transport_France2019$Qtt_Trsp_route)
X <- matrix( vec, ncol=4) 
Y=matrix(Transport_France2019$Qdieselcamion,n,1)
q=ncol(Y);
k=ncol(X);
K=k+1

 y=Y
 x=X
 
 nobs=cbind(1:n)
 
 OLS=lm(formula = y ~ x)
 
 summary(OLS)%>% pander
 
xc = cbind(1,x) 
bhat = OLS$coefficients 
yf = xc %*% bhat
res = y - yf
scr = t(res) %*% res


d1 = t(res) %*% res
d2 =  t(res[2:n]-res[1:n-1]) %*% (res[2:n]-res[1:n-1])
dw = d2/d1
print (dw)

ggplot()+
  geom_line(aes(x=Transport_France2019$Year, y=res, color="Résidus"))+
  geom_line(aes(x=Transport_France2019$Year, y=y, color="Valeur estimée de y \n par le modèle"))+
  geom_line(aes(x=Transport_France2019$Year, y=yf, color="Valeur réelle de y"))+
  labs(x = "Année", y = "Consommation de gazole par camion (en milliers de tonnes)", title = "Fig.8 Comparaison des résidus et \n des valeurs estimées par le modèle 1") + 
    theme(axis.text=element_text(size=7),axis.title=element_text(size=8),title = element_text(size=9), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))

```


```{r echo=FALSE, out.width = '70%', out.height = '70%', fig.align='center'}
n=length(Transport_France2019$Qdieselcamion[1:33])

P1 <- replicate(33, 0)
P1[1:16] <-  Transport_France2019$Pdiesel[1:16]/Transport_France2019$CPI[1:16]

P2 <- replicate(33, 0)
P2[17:33] <-  Transport_France2019$Pdiesel[17:33]/Transport_France2019$CPI[17:33]

vec <- c(P1,P2, Transport_France2019$"PIB en volume (en milliards d'euros 2014)"[1:33],Transport_France2019$Qtt_Trsp_route[1:33])
X <- matrix( vec, ncol=4) 
Y=matrix(Transport_France2019$Qdieselcamion[1:33],n,1)
q=ncol(Y);
k=ncol(X);
K=k+1
p=ncol(X)+1

 y=Y
 x=X
 
 nobs=cbind(1:n)
 
 OLS=lm(formula = y ~ x)
 
 summary(OLS)%>% pander
 
xc = cbind(1,x) 
bhat = OLS$coefficients 
yf = xc %*% bhat
res = y - yf
scr = t(res) %*% res


d1 = t(res) %*% res
d2 =  t(res[2:n]-res[1:n-1]) %*% (res[2:n]-res[1:n-1])
dw = d2/d1
print (dw)

ggplot()+
  geom_line(aes(x=Transport_France2019$Year[1:33], y=res, color="Résidus"))+
  geom_line(aes(x=Transport_France2019$Year[1:33], y=y, color="Valeur estimée de y \n par le modèle"))+
  geom_line(aes(x=Transport_France2019$Year[1:33], y=yf, color="Valeur réelle de y")) +
  labs(x = "Année", y = "Consommation de gazole par camion (en milliers de tonnes)", title = "Fig.9 Comparaison des résidus et \n des valeurs estimées par le modèle 2") + 
    theme(axis.text=element_text(size=7),axis.title=element_text(size=9),title = element_text(size=12), plot.title = element_text(hjust = 0.5, vjust = 0.5)) +
  scale_x_continuous(breaks=seq(1985,2020,5))

```
```{r echo=FALSE}

bgtest(y ~ x, order=2) %>% pander
```
```{r echo=FALSE}
jarque.bera.test(res) %>% pander
```

```{r echo=FALSE}
#sans terme croisé / pure test d'homoscédaticité
white_lm(OLS, interactions = FALSE, statonly = FALSE) %>% pander

bptest(y ~ x, varformula = NULL, studentize = TRUE, data = list()) %>% pander

```

```{r echo=FALSE}
Transport_France2019_prev <- read_excel("Transport_France2019_v2_prev.xlsx")

n=length(Transport_France2019$Qdieselcamion)
vec <- c(Transport_France2019$Pdiesel/Transport_France2019$CPI,Transport_France2019$"PIB en volume (en milliards d'euros 2014)",Transport_France2019$Qtt_Trsp_route)
X <- matrix( vec, ncol=3) 
Y=matrix(Transport_France2019$Qdieselcamion,n,1)


xc = cbind(1,x) 
xt = t(xc)
bmco = OLS$coefficients 
ycalc = xc %*% bmco
xtx= xt %*% xc
xtx1 = solve(xtx) 
u=y-xc%*%bmco
scr = t(u) %*% u
# prevision sur 4 periodes - forecasting over 4 periods
nprev=8
rmse=0
# X futur - future X : rmen[22:25]


X1 <- replicate(41, 0)
X1[1:16] <-  Transport_France2019_prev$Pdiesel[1:16]/Transport_France2019_prev$CPI[1:16]

X2 <- replicate(41, 0)
X2[17:41] <-  Transport_France2019_prev$Pdiesel[17:41]/Transport_France2019_prev$CPI[17:41]
X3 <- replicate(41, 0)
X3[1:41] <-  Transport_France2019_prev$"PIB en volume (en milliards d'euros 2014)"
X4 <- replicate(41, 0)
X4[1:41] <- Transport_France2019_prev$Qtt_Trsp_route

X1 <- replicate(8, 0)

X2 <-  Transport_France2019_prev$Pdiesel[34:41]/Transport_France2019_prev$CPI[34:41]

X3 <-  Transport_France2019_prev$"PIB en volume (en milliards d'euros 2014)"[34:41]

X4 <- Transport_France2019_prev$Qtt_Trsp_route[34:41]

z <- NULL
for( i in 1:8){
xf1<-X1[0+i]
xf2<-X2[0+i]
xf3<-X3[0+i]
xf4<-X4[0+i]
nvx <- matrix(c(1, xf1, xf2, xf3, xf4))
#

nvx1 = t(nvx);
#
# Prevision
#
nvy= nvx1 %*% bmco 
#
# Ecart-type de prevision
#
sprev= sqrt( (scr/(n-p)) * (1+ nvx1 %*% xtx1 %*% nvx ))
#
# T de Student
#
tstud=qt(0.975,n-p)
#
# Borne inf et sup d'un intervalle à 95%
#
prevymin=nvy-tstud*sprev
prevymax=nvy+tstud*sprev
z <-rbind(z,c(2017+i,nvy, prevymin, prevymax,sprev)) 
}

colnames(z) <- c("Année","Valeur de la prévison","Borne inférieure", "Borne supérieure", "Ecart-type de prévision")
kable(z, booktabs = T, linesep = "", caption = "Tableau des prévisions de 2017 à 2025") %>% 
kable_styling(latex_options = "hold_position", full_width = T,font_size = 7) %>% 
  row_spec(0, bold = T) %>% 
column_spec(1, bold = T)

rmse=sqrt(t(Transport_France2019_prev$Qdieselcamion[34:35]-z[1:2,2])%*% (Transport_France2019_prev$Qdieselcamion[34:35]-z[1:2,2])/2)
cat("Valeur de l'erreur quadratique moyenne RMSE (sur les années 2018 et 2019) :",rmse)

```
```{r eval=FALSE, include=FALSE}
Transport_France2019_prev <- read_excel("Transport_France2019_v2_prev.xlsx")

X1 <- replicate(8, 0)

X2 <-  Transport_France2019_prev$Pdiesel[34:41]/Transport_France2019_prev$CPI[34:41]

X3 <-  Transport_France2019_prev$"PIB en volume (en milliards d'euros 2014)"[34:41]

X4 <- Transport_France2019_prev$Qtt_Trsp_route[34:41]

data1 <- cbind(X1, X2, X3, X4)
data1 <- data.frame(data1)
prevy <- predict(OLS,data1,interval='prediction',na.action=na.omit)
nprev=8
rmse=sqrt(t(Transport_France2019_prev$Qdieselcamion[34:35]-prevy[1:2])%*% (Transport_France2019_prev$Qdieselcamion[34:35]-prevy[1:2])/2)
print(rmse)
```


